name = "gleam_httpc"
version = "2.1.2"
gleam = ">= 0.32.0"

licences = ["Apache-2.0"]
description = "Gleam bindings to Erlang's built in HTTP client, httpc"

repository = { type = "github", user = "gleam-lang", repo = "httpc" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[erlang]
extra_applications = ["inets", "ssl"]

[dependencies]
gleam_stdlib = "~> 0.32 or ~> 1.0"
gleam_http = "~> 3.0"

[dev-dependencies]
gleeunit = "~> 1.0"
